/**
 * Config plugin: inject the native App Intents Swift into the MAIN app target.
 *
 * `ios/` is gitignored and regenerated by `expo prebuild`, so the Swift source
 * lives committed under `native/ios/` and this plugin copies it into the
 * regenerated app target on every prebuild, then registers it in the app
 * target's "Compile Sources" build phase.
 *
 * The App Intents + AppShortcutsProvider must be in the MAIN app target (not a
 * separate extension) for them to auto-register with Shortcuts/Siri/Spotlight —
 * which is exactly what this plugin guarantees.
 */
const { withDangerousMod, withXcodeProject, IOSConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

/** Swift files (in native/ios/) to compile into the app target. */
const SWIFT_FILES = ['JarvisAppIntents.swift'];
const SOURCE_DIR = path.join('native', 'ios');

/** Copy the committed Swift sources into ios/<ProjectName>/. */
function withSwiftSourcesCopied(config) {
  return withDangerousMod(config, [
    'ios',
    (cfg) => {
      const { projectRoot, platformProjectRoot, projectName } = cfg.modRequest;
      const srcDir = path.join(projectRoot, SOURCE_DIR);
      const destDir = path.join(platformProjectRoot, projectName);
      for (const file of SWIFT_FILES) {
        fs.copyFileSync(path.join(srcDir, file), path.join(destDir, file));
      }
      return cfg;
    },
  ]);
}

/** Add the Swift files to the app target's Compile Sources build phase. */
function withSwiftSourcesLinked(config) {
  return withXcodeProject(config, (cfg) => {
    const project = cfg.modResults;
    const { projectName } = cfg.modRequest;
    for (const file of SWIFT_FILES) {
      const filepath = `${projectName}/${file}`;
      // Idempotent: skip if a previous (non-clean) prebuild already added it.
      if (project.hasFile(filepath)) continue;
      IOSConfig.XcodeUtils.addBuildSourceFileToGroup({
        filepath,
        groupName: projectName,
        project,
      });
    }
    return cfg;
  });
}

module.exports = function withJarvisAppIntents(config) {
  config = withSwiftSourcesCopied(config);
  config = withSwiftSourcesLinked(config);
  return config;
};
